server {
    listen 80;
    server_name question.coranqwq.xyz;
    root /srv/question-service/public;
    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }
    location / { return 503; }
}
